# Generated by Django 5.1.4 on 2024-12-17 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossMatchingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt_in_cc', models.FloatField()),
                ('blood_bank', models.CharField(max_length=255)),
                ('date_of_collection', models.DateField()),
                ('expiration_date', models.DateField()),
                ('result', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cross Matching Result',
                'verbose_name_plural': 'Cross Matching Result',
                'db_table': 'cross_matching_result',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('room_number', models.PositiveIntegerField()),
                ('sample_type', models.CharField(max_length=255)),
                ('time_of_collection', models.TimeField()),
                ('date_of_collection', models.DateField()),
                ('sars_result', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('physician', models.ForeignKey(limit_choices_to={'groups__name': 'Physicians'}, on_delete=django.db.models.deletion.CASCADE, related_name='physician', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hematology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemoglobin_mass_concentration', models.CharField(max_length=255)),
                ('hematocrit', models.CharField(max_length=255)),
                ('erythrocty_no_concentration', models.CharField(max_length=255)),
                ('platelet', models.FloatField()),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=255)),
                ('rh_type', models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], max_length=255)),
                ('leucocyte_no_concentration', models.FloatField()),
                ('segmenters', models.CharField(max_length=255)),
                ('lymphocytes', models.FloatField()),
                ('monocytes', models.FloatField()),
                ('eosinophils', models.FloatField()),
                ('basophils', models.FloatField()),
                ('others', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_hematology', to='hospital_app.patient')),
            ],
            options={
                'verbose_name': 'Hematology',
                'verbose_name_plural': 'Hematology',
                'db_table': 'hematology',
            },
        ),
        migrations.CreateModel(
            name='CrossMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_technologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_technologist', to=settings.AUTH_USER_MODEL)),
                ('pathologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathologist', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_matching_result', to='hospital_app.crossmatchingresult')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_cross_matching_result', to='hospital_app.patient')),
            ],
            options={
                'verbose_name': 'Cross Matching',
                'verbose_name_plural': 'Cross Matching',
                'db_table': 'cross_matching',
            },
        ),
        migrations.CreateModel(
            name='ClinicalChemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('triglycerides', models.FloatField()),
                ('hdl', models.FloatField()),
                ('ldl', models.FloatField()),
                ('creatinine', models.FloatField()),
                ('uric_acid', models.FloatField()),
                ('bun', models.FloatField()),
                ('sgpt', models.FloatField()),
                ('sgot', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_clinical_chemistry', to='hospital_app.patient')),
            ],
            options={
                'verbose_name': 'Clinical Chemistry',
                'verbose_name_plural': 'Clinical Chemistry',
                'db_table': 'clinical_chemistry',
            },
        ),
        migrations.CreateModel(
            name='Serology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hb_determination', models.CharField(max_length=255)),
                ('typhidot_rapid_test', models.CharField(max_length=255)),
                ('dengue_rapid_test', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_serology', to='hospital_app.patient')),
            ],
        ),
    ]
