# Generated by Django 5.1.4 on 2025-01-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossmatchingresult',
            name='blood_type',
            field=models.CharField(default='O', help_text='Name of the blood type', max_length=255),
            preserve_default=False,
        ),
    ]
