# Generated by Django 5.1.4 on 2024-12-17 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossmatching',
            name='medical_technologist',
            field=models.ForeignKey(help_text='Medical Technologist name', limit_choices_to={'groups__name': 'Medical Technologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_technologist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crossmatching',
            name='pathologist',
            field=models.ForeignKey(help_text='Pathologist name', limit_choices_to={'groups__name': 'Pathologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='pathologist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crossmatching',
            name='patient',
            field=models.ForeignKey(help_text='Patient name', on_delete=django.db.models.deletion.CASCADE, related_name='patient_cross_matching_result', to='hospital_app.patient'),
        ),
        migrations.AlterField(
            model_name='crossmatching',
            name='result',
            field=models.ForeignKey(help_text='Result of cross matching', on_delete=django.db.models.deletion.CASCADE, related_name='cross_matching_result', to='hospital_app.crossmatchingresult'),
        ),
        migrations.AlterField(
            model_name='crossmatchingresult',
            name='result',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='physician',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Physician'}, on_delete=django.db.models.deletion.CASCADE, related_name='physician', to=settings.AUTH_USER_MODEL),
        ),
    ]
