# Generated by Django 5.1.4 on 2025-01-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_crossmatchingresult_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
