# Generated by Django 5.1.4 on 2025-01-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_labrequest_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='is_done',
            field=models.BooleanField(default=False, help_text='Toggle if the request is done.'),
        ),
    ]
