# Generated by Django 5.1.4 on 2024-12-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_alter_hematology_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hematology',
            name='platelet',
            field=models.IntegerField(),
        ),
    ]
