# Generated by Django 5.1.4 on 2025-01-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_alter_patient_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='room_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(help_text='Serial number example: PT-01152025-R23', max_length=255),
        ),
    ]
