# Generated by Django 5.1.4 on 2024-12-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_alter_hematology_rh_type_employeeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='license_number',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
