# Generated by Django 5.1.4 on 2025-01-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_alter_patient_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_collection',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='room_number',
            field=models.PositiveIntegerField(blank=True, help_text='Leave room number as empty if out patient', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time_of_collection',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
