# Generated by Django 5.1.4 on 2024-12-24 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_hematology_assigned_pathologist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hematology',
            name='others',
        ),
        migrations.AlterField(
            model_name='hematology',
            name='assigned_pathologist',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Pathologist'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_pathologist', to=settings.AUTH_USER_MODEL),
        ),
    ]
