# Generated by Django 5.1.4 on 2025-01-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_alter_patient_date_of_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, help_text='Permanent address of the patient', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(blank=True, help_text='The birth date', null=True),
        ),
    ]
