# Generated by Django 5.1.4 on 2024-12-24 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0010_alter_hematology_assigned_pathologist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalchemistry',
            name='assigned_pathologist',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Pathologist'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_chemist_pathologist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalchemistry',
            name='assigned_technologist',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Medical Technologist'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_chemist_technologist', to=settings.AUTH_USER_MODEL),
        ),
    ]
