# Generated by Django 5.1.4 on 2024-12-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0013_patient_assigned_pathologist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('In Patient', 'In Patient'), ('Out Patient', 'Out Patient')], default='In Patient', max_length=100),
        ),
    ]
