# Generated by Django 5.1.4 on 2024-12-26 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0014_patient_patient_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('assigned_pathologist', models.ForeignKey(limit_choices_to={'groups__name': 'Pathologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='rbs_assigned_pathologist', to=settings.AUTH_USER_MODEL)),
                ('assigned_technologist', models.ForeignKey(limit_choices_to={'groups__name': 'Medical Technologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='rbs_assigned_technologist', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_rbs', to='hospital_app.patient')),
            ],
        ),
    ]
