# Generated by Django 5.1.4 on 2024-12-26 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0015_rbs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Urinalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('appearance', models.CharField(max_length=255)),
                ('specific_gravity', models.CharField(max_length=255)),
                ('pH', models.CharField(max_length=255)),
                ('sugar', models.CharField(max_length=255)),
                ('albumin', models.CharField(max_length=255)),
                ('epithelia', models.CharField(max_length=255)),
                ('bacteria', models.CharField(max_length=255)),
                ('pus_cells', models.CharField(max_length=255)),
                ('rbc', models.CharField(max_length=255)),
                ('cast', models.CharField(max_length=255)),
                ('crystals', models.CharField(max_length=255)),
                ('others', models.CharField(max_length=255)),
                ('amorphous', models.CharField(max_length=255)),
                ('mucous_thread', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('assigned_pathologist', models.ForeignKey(limit_choices_to={'groups__name': 'Pathologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='urinalysis_assigned_pathologist', to=settings.AUTH_USER_MODEL)),
                ('assigned_technologist', models.ForeignKey(limit_choices_to={'groups__name': 'Medical Technologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='urinalysis_assigned_technologist', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_urinalysis', to='hospital_app.patient')),
            ],
        ),
    ]
