# Generated by Django 5.1.4 on 2024-12-26 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0016_urinalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='urinalysis',
            name='pregnancy_test',
            field=models.CharField(blank=True, help_text='Pregnancy Test', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='urates',
            field=models.CharField(blank=True, help_text='Urates', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='albumin',
            field=models.CharField(help_text='Albumin', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='amorphous',
            field=models.CharField(help_text='Amorphous', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='appearance',
            field=models.CharField(help_text='Appearance', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='assigned_pathologist',
            field=models.ForeignKey(help_text='Pathologist name', limit_choices_to={'groups__name': 'Pathologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='urinalysis_assigned_pathologist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='assigned_technologist',
            field=models.ForeignKey(help_text='Medical Technologist name', limit_choices_to={'groups__name': 'Medical Technologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='urinalysis_assigned_technologist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='bacteria',
            field=models.CharField(help_text='Bacteria', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='cast',
            field=models.CharField(help_text='Cast', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='color',
            field=models.CharField(help_text='Color', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='crystals',
            field=models.CharField(help_text='Crystals', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='epithelia',
            field=models.CharField(help_text='Epithelia', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='mucous_thread',
            field=models.CharField(help_text='Mucous Thread', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='others',
            field=models.CharField(help_text='Others', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='pH',
            field=models.CharField(help_text='pH', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='pus_cells',
            field=models.CharField(help_text='Pus Cells', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='rbc',
            field=models.CharField(help_text='RBC', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='specific_gravity',
            field=models.CharField(help_text='Specific Gravity', max_length=255),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='sugar',
            field=models.CharField(help_text='Sugar', max_length=255),
        ),
    ]
