# Generated by Django 5.1.4 on 2024-12-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0017_urinalysis_pregnancy_test_urinalysis_urates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossmatchingresult',
            name='serial_no',
            field=models.CharField(default='21-65894', max_length=255),
            preserve_default=False,
        ),
    ]
