# Generated by Django 5.1.4 on 2024-12-26 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0018_crossmatchingresult_serial_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crossmatching',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cross Matching', 'verbose_name_plural': 'Cross Matchings'},
        ),
        migrations.AlterModelOptions(
            name='crossmatchingresult',
            options={'ordering': ['-date_of_collection'], 'verbose_name': 'Cross Matching Result', 'verbose_name_plural': 'Cross Matching Results'},
        ),
        migrations.RemoveField(
            model_name='crossmatching',
            name='result',
        ),
        migrations.AddField(
            model_name='crossmatching',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp of record creation.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crossmatching',
            name='results',
            field=models.ManyToManyField(help_text='Related cross-matching results.', related_name='cross_matchings', to='hospital_app.crossmatchingresult'),
        ),
        migrations.AddField(
            model_name='crossmatching',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of last update.'),
        ),
        migrations.AlterField(
            model_name='crossmatching',
            name='medical_technologist',
            field=models.ForeignKey(help_text='Medical technologist handling the cross-matching.', limit_choices_to={'groups__name': 'Medical Technologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='technologist_cross_matchings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crossmatching',
            name='pathologist',
            field=models.ForeignKey(help_text='Pathologist overseeing the cross-matching.', limit_choices_to={'groups__name': 'Pathologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='pathologist_cross_matchings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crossmatching',
            name='patient',
            field=models.ForeignKey(help_text='Patient associated with this cross-matching.', on_delete=django.db.models.deletion.CASCADE, related_name='cross_matchings', to='hospital_app.patient'),
        ),
        migrations.AlterField(
            model_name='crossmatchingresult',
            name='amt_in_cc',
            field=models.FloatField(help_text='Amount in cc.'),
        ),
        migrations.AlterField(
            model_name='crossmatchingresult',
            name='blood_bank',
            field=models.CharField(help_text='Name of the blood bank.', max_length=255),
        ),
        migrations.AlterField(
            model_name='crossmatchingresult',
            name='date_of_collection',
            field=models.DateField(help_text='Date the blood was collected.'),
        ),
        migrations.AlterField(
            model_name='crossmatchingresult',
            name='expiration_date',
            field=models.DateField(help_text='Expiration date of the blood.'),
        ),
        migrations.AlterField(
            model_name='crossmatchingresult',
            name='result',
            field=models.TextField(help_text='Result of the cross-matching.', max_length=255),
        ),
        migrations.AlterField(
            model_name='crossmatchingresult',
            name='serial_no',
            field=models.CharField(help_text='Unique serial number of the cross-matching result.', max_length=255, unique=True),
        ),
    ]
