# Generated by Django 5.1.4 on 2024-12-29 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0021_remove_rbsresult_assigned_pathologist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description for laboratory request', max_length=300)),
                ('lab_request_type', models.CharField(choices=[('Clinical Chemistry', 'Clinical Chemistry'), ('Cross Matching', 'Cross Matching'), ('Urinalysis', 'Urinalysis'), ('Hematology', 'Hematology'), ('Serology', 'Serology'), ('RBS', 'RBS')], help_text='Type of laboratory request', max_length=255)),
                ('date_request', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(help_text='Patient needs to be examine', on_delete=django.db.models.deletion.CASCADE, related_name='patient_lab_requests', to='hospital_app.patient')),
            ],
        ),
    ]
