# Generated by Django 5.1.4 on 2025-01-01 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0023_labrequest_requested_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalchemistry',
            options={'ordering': ('date',), 'verbose_name': 'Clinical Chemistry', 'verbose_name_plural': 'Clinical Chemistry'},
        ),
        migrations.AlterModelOptions(
            name='hematology',
            options={'ordering': ('date',), 'verbose_name': 'Hematology', 'verbose_name_plural': 'Hematology'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('time_of_collection',)},
        ),
        migrations.AlterModelOptions(
            name='rbsresult',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='urinalysis',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='requested_by',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Doctor'), ('groups__name', 'Nurse'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='requested_by_lab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middlename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
