# Generated by Django 5.1.4 on 2025-01-10 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0025_clinicalchemistry_re_test_crossmatching_re_test_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalchemistry',
            name='re_test',
            field=models.BooleanField(default=False, help_text='Re-test clinical chemistry results'),
        ),
        migrations.AlterField(
            model_name='crossmatching',
            name='re_test',
            field=models.BooleanField(default=False, help_text='Re-test the cross-matching'),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='re_test',
            field=models.BooleanField(default=False, help_text='Re-test Hematology'),
        ),
        migrations.AlterField(
            model_name='rbs',
            name='re_test',
            field=models.BooleanField(default=False, help_text='Retest the RBS'),
        ),
        migrations.AlterField(
            model_name='serology',
            name='re_test',
            field=models.BooleanField(default=False, help_text='Re-test serology'),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='re_test',
            field=models.BooleanField(default=False, help_text='Re-test urinalysis'),
        ),
    ]
