# Generated by Django 5.1.4 on 2025-01-10 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0027_alter_employeeinfo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossmatching',
            name='medical_technologist',
            field=models.ForeignKey(blank=True, help_text='Medical technologist handling the cross-matching.', limit_choices_to={'groups__name': 'Medical Technologist'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologist_cross_matchings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crossmatching',
            name='pathologist',
            field=models.ForeignKey(blank=True, help_text='Pathologist overseeing the cross-matching.', limit_choices_to={'groups__name': 'Pathologist'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathologist_cross_matchings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='assigned_pathologist',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Pathologist'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_pathologist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='assigned_technologist',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Medical Technologist'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_technologist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'Doctor'), ('groups__name', 'Nurse'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by_lab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='assigned_pathologist',
            field=models.ForeignKey(blank=True, help_text='Pathologist name', limit_choices_to={'groups__name': 'Pathologist'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urinalysis_assigned_pathologist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urinalysis',
            name='assigned_technologist',
            field=models.ForeignKey(blank=True, help_text='Medical Technologist name', limit_choices_to={'groups__name': 'Medical Technologist'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urinalysis_assigned_technologist', to=settings.AUTH_USER_MODEL),
        ),
    ]
